#include "daq.h"

#include "debug_strings.h"

#include "mcp9808.h"

#include "integer.h"
#include <string.h>
#include <math.h>
#include "stdio.h"

#include "ff.h"
#include "fatfs.h"

#include "stm32l4xx_hal.h"

/* ── External peripheral handles (generated by CubeMX / defined in main.c) */

extern ADC_HandleTypeDef hadc1;
extern CRC_HandleTypeDef hcrc;
extern DAC_HandleTypeDef hdac1;
extern SMBUS_HandleTypeDef hsmbus1;
extern IWDG_HandleTypeDef hiwdg;
extern RTC_HandleTypeDef hrtc;
extern SPI_HandleTypeDef hspi2;
extern TIM_HandleTypeDef htim2;
extern void SystemClock_Config(void);
extern void MX_ADC1_Init(void);
extern void MX_USART2_UART_Init(void);

/* ── Global state ────────────────────────────────────────────────────────
 *
 *  Placed in .noinit so Stop 2 mode does not zero them on wake.
 *  The cold-boot check in main.c zeros them once at power-on.
 */
__attribute__((section(".noinit"))) DaqContext   g_daq;
__attribute__((section(".noinit"))) FaultManager g_fault_mgr;
__attribute__((section(".noinit"))) PendingFault g_pending_fault;
__attribute__((section(".noinit"))) AcqState     g_acq;

/* ── RAM-retentive log buffer ────────────────────────────────────────── */

__attribute__((section(".noinit")))
static MeasurementRecord s_record_buf[RAM_BUFFER_DEPTH];

__attribute__((section(".noinit")))
static FaultLog Failed_Fault_Logs[FAILED_LOG_BUFFER];

__attribute__((section(".noinit")))
uint8_t s_buf_head = 0u;

/* uint16_t, not uint8_t: FAILED_LOG_BUFFER (1024) doesn't fit in a
 * uint8_t (max 255) -- with a narrower type this counter wraps at 256
 * and the buffer's upper 3/4 is never written to; the compiler flags the
 * `< FAILED_LOG_BUFFER` check below as always-true as a result. */
__attribute__((section(".noinit")))
uint16_t fault_buf_head = 0u;

/*
 * SD card structures
 */
/* ── External FatFS handles (Generated by CubeMX in ff_gen_drv.c / fatfs.c) */

extern FATFS USERFatFS;    /* Linked to SDFatFS in your code */
extern FIL   USERFile;     /* Linked to SDFile in your code */
extern char  USERPath[4];  /* Linked to SDPath in your code */
FRESULT ret;    		/* Return value for USER */

FaultType fault = FAULT_NONE;

/* To make your code readable without changing every line,
   we can use macros to map the names: */
#define SDFatFS USERFatFS
#define SDFile   USERFile
#define SDPath   USERPath

/* ── Debug name tables (declared extern in debug_strings.h) ───────────── */

const char *const FAULT_NAMES[] = {
    "NONE",
    "HEALTH_CHECK",
    "INVALID_DETECTOR_RESPONSE",
    "STORAGE_FAILURE",
    "LOAD_SWITCH_DETECTION",
    "LOAD_SWITCH_EXCITATION",
    "LOAD_SWITCH_SDCARD",
    "DAC_ERROR",
    "ADC_TIMEOUT",
    "TEMP_SENSOR",
    "TEMP_ALERT",
    "CRC_MISMATCH",
    "NULL_POINTER",
    "BUFFER_FULL"
};

const char *const SUBSYS_NAMES[] = {
    "PROCESSOR",
    "DETECTION",
    "EXCITATION",
    "SDCARD",
    "TEMP_SENSOR"
};

const char *const STATE_NAMES[] = {
    "STOP",
    "INIT",
    "POWER_SEQ",
    "BASELINE",
    "ACQUIRE",
    "PROCESS",
    "LOG",
    "FAULT"
};

/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 1 — Internal helpers
 * ══════════════════════════════════════════════════════════════════════ */

__STATIC_FORCEINLINE void power_domain_set(GPIO_TypeDef *port, uint16_t pin,
                                           GPIO_PinState state)
{
    HAL_GPIO_WritePin(port, pin, state);
}

/** Returns 1 if the active-low fault pin is asserted (line pulled low). */
__STATIC_FORCEINLINE uint8_t fault_pin_asserted(GPIO_TypeDef *port, uint16_t pin)
{
    return (HAL_GPIO_ReadPin(port, pin) == GPIO_PIN_RESET) ? 1u : 0u;
}


/* Maps the 12 bit ADC value to a voltage value between 0V-3.3V*/
float fmap(uint16_t x) {
  return (x - 0.0) * (3.3 - 0.0) / (4095 - 0.0) + 0.0;
}


/** Build a 32-bit epoch-like timestamp from the RTC*/
static uint32_t rtc_now(void)
{
    RTC_TimeTypeDef t;
    RTC_DateTypeDef d;
    
    HAL_RTC_GetTime(&hrtc, &t, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&hrtc, &d, RTC_FORMAT_BIN);
    return (uint32_t)t.Seconds
    		+ ((uint32_t)t.Minutes * 60u)
			+ ((uint32_t)t.Hours   * 3600u);
}

static void date_and_time(char * buffer)	{
	/* Variables to hold date and time */
	RTC_DateTypeDef sDate;
	RTC_TimeTypeDef sTime;

	/* 1. Get the current Time */
	HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);

	/* 2. Get the current Date (MUST be called after GetTime) */
	HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN);

	/* 3. Format and print via UART */
	sprintf(buffer, "20%02d-%02d-%02d %02d:%02d:%02d\r\n",
	        sDate.Year, sDate.Month, sDate.Date,
	        sTime.Hours, sTime.Minutes, sTime.Seconds);
}

/* Encode a signed Celsius value into the MCP9808 two-byte boundary format. */
static void encode_mcp9808_limit(float celsius, uint8_t out[2])
{
    int16_t raw = (int16_t)(celsius * 16.0f);  /* 0.0625 °C per LSB, upper 3 bits */
    raw <<= 2;                                  /* Bits [15:2] in the 16-bit word   */
    out[0] = (uint8_t)((raw >> 8) & 0xFF);
    out[1] = (uint8_t)( raw       & 0xFF);
}


/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 2 — ISR callbacks
 * ══════════════════════════════════════════════════════════════════════ */

/* ── 2a. Load-switch fault callbacks ─────────────────────────────────── */
void DAQ_EXTI_Detection_Callback(void)
{
    if (g_pending_fault.type == FAULT_NONE) {
        g_pending_fault.type      = FAULT_LOAD_SWITCH_DETECTION;
        g_pending_fault.subsystem = SUBSYS_DETECTION;
    }
    /* Also abort any in-progress acquisition */
    if (g_acq.phase != ACQ_IDLE) {
        g_acq.fault = FAULT_LOAD_SWITCH_DETECTION;
    }
}

void DAQ_EXTI_Excitation_Callback(void)
{
    if (g_pending_fault.type == FAULT_NONE) {
        g_pending_fault.type      = FAULT_LOAD_SWITCH_EXCITATION;
        g_pending_fault.subsystem = SUBSYS_EXCITATION;
    }
    if (g_acq.phase != ACQ_IDLE) {
        g_acq.fault = FAULT_LOAD_SWITCH_EXCITATION;
    }
}

void DAQ_EXTI_SDCard_Callback(void)
{
    if (g_pending_fault.type == FAULT_NONE) {
        g_pending_fault.type      = FAULT_LOAD_SWITCH_SDCARD;
        g_pending_fault.subsystem = SUBSYS_SDCARD;
    }
}


/* ── 2b. Timer period-elapsed callback (500 ms tick) ────────────────────
 *
 *  This is the heart of the acquisition engine. On every tick we advance
 *  the AcqPhase state machine by one step:
 *
 *    ACQ_WAIT_OFF  → ACQ_SAMPLE_OFF  (excitation already off; trigger ADC)
 *    ACQ_SAMPLE_OFF→ ACQ_WAIT_ON     (turn excitation ON; let filter settle)
 *    ACQ_WAIT_ON   → ACQ_SAMPLE_ON   (trigger ADC)
 *    ACQ_SAMPLE_ON → ACQ_WAIT_OFF    (turn excitation OFF; increment pair)
 *
 *  The ADC conversion is started here; DAQ_ADC_ConvCplt_Callback() stores
 *  the result. The timer keeps running; main loop only reads g_acq.complete.
 * ─────────────────────────────────────────────────────────────────────── */

void DAQ_TIM_PeriodElapsed_Callback(void)
{
    /* Bail immediately if a fault is already pending */
    if (g_acq.fault != FAULT_NONE || g_pending_fault.type != FAULT_NONE) {
        HAL_TIM_Base_Stop_IT(&htim2);
        g_acq.complete = 1u;
        g_acq.fault    = (g_acq.fault != FAULT_NONE)
                         ? g_acq.fault
                         : g_pending_fault.type;
        return;
    }

    switch (g_acq.phase)
    {
        case ACQ_WAIT_OFF:
            /* Filter has settled with excitation off — trigger ADC */
            g_acq.phase = ACQ_SAMPLE_OFF;
            HAL_ADC_Start_IT(&hadc1);
            break;

        case ACQ_WAIT_ON:
            /* Filter has settled with excitation on — trigger ADC */
            g_acq.phase = ACQ_SAMPLE_ON;
            HAL_ADC_Start_IT(&hadc1);
            break;

        /*
         * ACQ_SAMPLE_OFF and ACQ_SAMPLE_ON transitions are driven by
         * DAQ_ADC_ConvCplt_Callback() once the conversion is done.
         */
        default:
            break;
    }
}

/* ── 2d. ADC conversion complete callback ───────────────────────────────
 *
 *  Stores the converted value into the correct buffer slot and advances
 *  AcqPhase.
 * ─────────────────────────────────────────────────────────────────────── */

void DAQ_ADC_ConvCplt_Callback(void)
{
    uint16_t value = (uint16_t)HAL_ADC_GetValue(&hadc1);

    switch (g_acq.phase)
    {
        case ACQ_SAMPLE_OFF:
            g_acq.buf_off[g_acq.pair_count] = value;
            /* Turn excitation ON now — filter settles over next half-period */
            power_domain_set(EXCITE_EN_PORT, EXCITE_EN_PIN, GPIO_PIN_SET);
            g_acq.phase = ACQ_WAIT_ON;
            break;

        case ACQ_SAMPLE_ON:
            g_acq.buf_on[g_acq.pair_count] = value;
            g_acq.pair_count++;

            if (g_acq.pair_count >= ACQUISITION_PAIRS) {
                /* Window complete — stop timer, turn excitation off */
                HAL_TIM_Base_Stop_IT(&htim2);
                power_domain_set(EXCITE_EN_PORT, EXCITE_EN_PIN, GPIO_PIN_RESET);
                HAL_DAC_Stop(&hdac1, DAC_CHANNEL_1);
                g_acq.phase    = ACQ_IDLE;
                g_acq.complete = 1u;
            } else {
                /* Turn excitation OFF — filter settles over next half-period */
                power_domain_set(EXCITE_EN_PORT, EXCITE_EN_PIN, GPIO_PIN_RESET);
                g_acq.phase = ACQ_WAIT_OFF;
            }
            break;

        default:
            break;
    }
}

/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 3 — Power sequencing
 *
 *  Each domain is enabled individually. A settling delay is followed by
 *  a synchronous fault-pin poll so a bad domain is caught before the
 *  next stage is activated.
 * ══════════════════════════════════════════════════════════════════════ */
FaultType init_power_domain(GPIO_TypeDef *en_port, uint16_t en_pin,
                            GPIO_TypeDef *flt_port, uint16_t flt_pin,
                            uint32_t settle_delay_ms, FaultType expected_fault)
{
    power_domain_set(en_port, en_pin, GPIO_PIN_SET);
    HAL_Delay(settle_delay_ms);

    if (g_pending_fault.type != FAULT_NONE || fault_pin_asserted(flt_port, flt_pin))
    {
        power_domain_set(en_port, en_pin, GPIO_PIN_RESET);
        return expected_fault;
    }
    return FAULT_NONE;
}

/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 4 — Health check and detector validation
 * ══════════════════════════════════════════════════════════════════════ */

FaultType check_power_health(void)
{
    if (g_pending_fault.type != FAULT_NONE) {
        return g_pending_fault.type;
    }

    /* Only check domains that are currently supposed to be ON */
    if (fault_pin_asserted(DETECT_FLT_PORT, DETECT_FLT_PIN)) {
        g_pending_fault.type      = FAULT_LOAD_SWITCH_DETECTION;
        g_pending_fault.subsystem = SUBSYS_DETECTION;
        return FAULT_LOAD_SWITCH_DETECTION;
    }

    /* Excitation fault is checked dynamically inside the sampling loop */

    return FAULT_NONE;
}

FaultType check_detector_response(uint16_t adc_delta)
{
    return (adc_delta < DETECTOR_THRESHOLD)
           ? FAULT_INVALID_DETECTOR_RESPONSE
           : FAULT_NONE;
}

/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 5 — Timer-driven acquisition
 *
 *  start_acquisition() resets AcqState, starts the excitation DAC,
 *  turns excitation OFF (first half-period is always OFF to get the
 *  baseline sample), then starts the 500 ms timer. The ISR does the
 *  rest. main.c polls g_acq.complete.
 * ══════════════════════════════════════════════════════════════════════ */

FaultType start_acquisition(void)
{
    /* Reset acquisition state */
    memset(&g_acq, 0, sizeof(AcqState));
    g_acq.phase = ACQ_WAIT_OFF;

    /* DAC sets the excitation reference level */
    if (HAL_DAC_SetValue(&hdac1, DAC_CHANNEL_1, DAC_ALIGN_12B_R, 2048u) != HAL_OK
        || HAL_DAC_Start(&hdac1, DAC_CHANNEL_1) != HAL_OK)
    {
        return FAULT_DAC_ERROR;
    }

    /* Ensure excitation is OFF for the first half-period */
    power_domain_set(EXCITE_EN_PORT, EXCITE_EN_PIN, GPIO_PIN_RESET);

    /* Start the 500 ms timer — ISR drives phase transitions from here */
    HAL_TIM_Base_Stop_IT(&htim2);
    __HAL_TIM_SET_COUNTER(&htim2, 0u);
    HAL_StatusTypeDef result = HAL_TIM_Base_Start_IT(&htim2);
    if (result != HAL_OK) {
        return FAULT_DAC_ERROR;   /* No dedicated timer fault; reuse DAC error */
    }

    return FAULT_NONE;
}

/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 6 — Processing
 * ══════════════════════════════════════════════════════════════════════ */
/**
 * @brief Computes mean and sample standard deviation in a single pass.
 */
void compute_stats(const uint16_t *buf, size_t n, float *mean, float *stddev)
{
    if (n == 0) {
        *mean = 0.0f;
        *stddev = 0.0f;
        return;
    }

    float m = 0.0f;
    float s = 0.0f;

    for (size_t i = 0; i < n; i++) {
        float val = (float)buf[i];
        float m_prev = m;

        m += (val - m) / (i + 1);
        s += (val - m_prev) * (val - m);
    }

    *mean = m;
    *stddev = sqrtf(s / (n - 1));
}

FaultType process_measurement(const uint16_t *on_buf,
                               const uint16_t *off_buf,
                               size_t n,
                               MeasurementRecord *out)
{
    if (on_buf == NULL || off_buf == NULL || out == NULL) return FAULT_NULL_POINTER;

    float mean_on, stddev_on;
	float mean_off, stddev_off;

	/* 1. Compute stats in a single pass for both buffers */
	compute_stats(on_buf, n, &mean_on, &stddev_on);
	compute_stats(off_buf, n, &mean_off, &stddev_off);

	/* 2. Calculate the raw differential */
	float raw_diff = mean_on - mean_off;

	/* 3. Sanity Check: Did the detector actually see the LED turn on? */
	FaultType det_fault = check_detector_response((uint16_t)(fabsf(raw_diff) > 0.0f ? raw_diff : 0.0f));
	if (det_fault != FAULT_NONE) {
		return det_fault; /* Fatal: Tell the main loop to abort and retry */
	}

	/* 4. Temperature compensation */
	float temperature = TEMP_REF_CELSIUS;
	FaultType temp_st = read_mcp9808_temp(&temperature);
	float comp = 1.0f + (TEMP_ALPHA * (temperature - TEMP_REF_CELSIUS));
	if (comp <= 0.0f) comp = 1.0f;  /* Guard against div/0 */

	/* 5. Populate record */
	out->adc_differential = fmap(raw_diff);
	out->adc_stddev       = fmap(stddev_on); /* We log the noise of the 'ON' signal */
	out->temperature_c    = temperature;
	out->cycle_count	  = g_daq.cycle_count;
	out->timestamp        = rtc_now();
	out->op_status        = temp_st;   /* Log if temp failed, but don't abort cycle */

	/* 6. Compute and append CRC over all preceding fields */
	out->crc32 = crc32_record(out);

	return FAULT_NONE; /* Processing succeeded, record is ready to log */
}

/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 7 — MCP9808 temperature sensor
 * ══════════════════════════════════════════════════════════════════════ */

/**
 * configure_mcp9808_alert()
 *
 * Called once at startup.
 */
FaultType configure_mcp9808_alert(void)
{
    uint8_t cmd[3];

    /* Write TUPPER */
    cmd[0] = MCP9808_REG_TUPPER;
    encode_mcp9808_limit(TEMP_ALERT_UPPER_C, &cmd[1]);
    if (HAL_SMBUS_Master_Transmit_IT(&hsmbus1, MCP9808_I2C_ADDR, cmd, 3u, SMBUS_FIRST_AND_LAST_FRAME_NO_PEC) != HAL_OK)
        return FAULT_TEMP_SENSOR;
    while (HAL_SMBUS_GetState(&hsmbus1) != HAL_SMBUS_STATE_READY);

    /* Write TLOWER */
    cmd[0] = MCP9808_REG_TLOWER;
    encode_mcp9808_limit(TEMP_ALERT_LOWER_C, &cmd[1]);
    if (HAL_SMBUS_Master_Transmit_IT(&hsmbus1, MCP9808_I2C_ADDR, cmd, 3u, SMBUS_FIRST_AND_LAST_FRAME_NO_PEC) != HAL_OK)
        return FAULT_TEMP_SENSOR;
    while (HAL_SMBUS_GetState(&hsmbus1) != HAL_SMBUS_STATE_READY);

    /* Write TCRIT */
    cmd[0] = MCP9808_REG_TCRIT;
    encode_mcp9808_limit(TEMP_ALERT_CRIT_C, &cmd[1]);
    if (HAL_SMBUS_Master_Transmit_IT(&hsmbus1, MCP9808_I2C_ADDR, cmd, 3u, SMBUS_FIRST_AND_LAST_FRAME_NO_PEC) != HAL_OK)
        return FAULT_TEMP_SENSOR;
    while (HAL_SMBUS_GetState(&hsmbus1) != HAL_SMBUS_STATE_READY);

    /* Config register: enable alert output */
    cmd[0] = MCP9808_REG_CONFIG;
    cmd[1] = 0x00u;
    cmd[2] = 0x01u;
    if (HAL_SMBUS_Master_Transmit_IT(&hsmbus1, MCP9808_I2C_ADDR, cmd, 3u, SMBUS_FIRST_AND_LAST_FRAME_NO_PEC) != HAL_OK)
        return FAULT_TEMP_SENSOR;
    while (HAL_SMBUS_GetState(&hsmbus1) != HAL_SMBUS_STATE_READY);

    return FAULT_NONE;
}

FaultType read_mcp9808_temp(float *temp_c)
{
    if (temp_c == NULL) return FAULT_NULL_POINTER;

    /* Wake: clear shutdown bit */
    uint8_t wake[3] = { MCP9808_REG_CONFIG, 0x00u, 0x01u };
    HAL_SMBUS_Master_Transmit_IT(&hsmbus1, MCP9808_I2C_ADDR, wake, 3u, SMBUS_FIRST_AND_LAST_FRAME_NO_PEC);
    while (HAL_SMBUS_GetState(&hsmbus1) != HAL_SMBUS_STATE_READY);

    HAL_Delay(250u);   /* Wait for conversion */

    /* Select ambient temperature register */
    uint8_t reg = MCP9808_REG_TAMBIENT;
    uint8_t data[2];

    /* Request data: Send Reg address then Receive 2 bytes */
    HAL_SMBUS_Master_Transmit_IT(&hsmbus1, MCP9808_I2C_ADDR, &reg, 1u, SMBUS_FIRST_AND_LAST_FRAME_NO_PEC);
    while (HAL_SMBUS_GetState(&hsmbus1) != HAL_SMBUS_STATE_READY);

    if (HAL_SMBUS_Master_Receive_IT(&hsmbus1, MCP9808_I2C_ADDR, data, 2u, SMBUS_FIRST_AND_LAST_FRAME_NO_PEC) != HAL_OK)
        return FAULT_TEMP_SENSOR;
    while (HAL_SMBUS_GetState(&hsmbus1) != HAL_SMBUS_STATE_READY);

    /* Parse temperature data (Existing logic) */
    uint8_t upper = data[0] & 0x1Fu;
    uint8_t lower = data[1];
    float temp;
    if (upper & 0x10u) {
        upper &= 0x0Fu;
        temp = 256.0f - ((float)upper * 16.0f + (float)lower / 16.0f);
    } else {
        temp = (float)upper * 16.0f + (float)lower / 16.0f;
    }

    /* Shutdown: set bit 8 */
    uint8_t sleep[3] = { MCP9808_REG_CONFIG, 0x01u, 0x00u };
    HAL_SMBUS_Master_Transmit_IT(&hsmbus1, MCP9808_I2C_ADDR, sleep, 3u, SMBUS_FIRST_AND_LAST_FRAME_NO_PEC);
    while (HAL_SMBUS_GetState(&hsmbus1) != HAL_SMBUS_STATE_READY);

    *temp_c = temp;
    return FAULT_NONE;
}

/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 8 — CRC integrity
 * ══════════════════════════════════════════════════════════════════════ */
uint32_t crc32_record(const MeasurementRecord *rec)
{
    const uint32_t data_bytes = (uint32_t)offsetof(MeasurementRecord, crc32);
    const uint32_t word_count = data_bytes / sizeof(uint32_t);

    __HAL_CRC_DR_RESET(&hcrc);
    /* Standard CRC-32 involves a final XOR with 0xFFFFFFFF. */
    return HAL_CRC_Calculate(&hcrc, (uint32_t *)rec, word_count) ^ 0xFFFFFFFF;
}

FaultType verify_record_crc(const MeasurementRecord *rec)
{
    if (rec == NULL) return FAULT_NULL_POINTER;
    uint32_t expected = crc32_record(rec);
    return (expected == rec->crc32) ? FAULT_NONE : FAULT_CRC_MISMATCH;
}


/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 9 — Logging
 * ══════════════════════════════════════════════════════════════════════ */

FaultType log_measurement(const MeasurementRecord *record)
{
    if (record == NULL)                 return FAULT_NULL_POINTER;
    if (s_buf_head >= RAM_BUFFER_DEPTH) return FAULT_BUFFER_FULL;

    /* Verify CRC before accepting the record into the buffer */
    FaultType crc_status = verify_record_crc(record);
    if (crc_status != FAULT_NONE) return crc_status;

    /* 1. Get the readable Status string from our lookup table */
	const char* status_str = (record->op_status < FAULT_NAMES_COUNT) ?
							 FAULT_NAMES[record->op_status] : "UNKNOWN";

	/* 2. Format a professional debug block for Hercules */
	char buffer[64];
	date_and_time(buffer);
	printf("\n--- NEW MEASUREMENT RECORD ---\n");

	printf("%-16s : %s\n",    "Timestamp",     		buffer);
	printf("%-16s : %.4f\n",  "Measurement (V)",   	record->adc_differential);
	printf("%-16s : %.4f\n",  "Noise (SD)",    		record->adc_stddev);
	printf("%-16s : %.2f C\n","Temperature",   		record->temperature_c);
	printf("%-16s : %d\n",    "Cycle Count",   		record->cycle_count);
	printf("%-16s : %s\n",    "Fault status",  		status_str);
	printf("%-16s : 0x%08lX\n","Integrity",    		record->crc32);

	printf("------------------------------\n");

    s_record_buf[s_buf_head++] = *record;

    if (s_buf_head >= RAM_BUFFER_DEPTH) {
    	/* Deliberately not auto-flushing here: flush_buffer_to_sd() powers
    	 * the SD domain, which the caller may not want mid-cycle. Report
    	 * full and let the caller decide when to flush. */
    	printf("![WARNING] RAM Buffer Full - Storage Unavailable\n");
    	return FAULT_STORAGE_FAILURE;
    }
    return FAULT_NONE;
}

FaultType log_fault_to_sd(const FaultLog *entry)
{
	if (entry == NULL) return FAULT_NULL_POINTER;

	FaultType fault = FAULT_NONE;

    fault = init_power_domain(SDCARD_EN_PORT, SDCARD_EN_PIN,
            			SDCARD_FLT_PORT, SDCARD_FLT_PIN,
						DELAY_SDCARD_SETTLE_MS,
						FAULT_LOAD_SWITCH_SDCARD);

    if (fault != FAULT_NONE) return fault;

    ret = f_mount(&SDFatFS, (TCHAR const*)SDPath, 1);
    if (ret != FR_OK) 	{
		fault =  FAULT_STORAGE_FAILURE;
    }

    if (ret == FR_OK)
	{
    	ret = f_open(&SDFile, "FAULTS.CSV", FA_OPEN_APPEND | FA_WRITE);
    	if (ret == FR_OK) {
			char msg[128];
			const char *fault_name = (entry->fault < FAULT_NAMES_COUNT)
			                         ? FAULT_NAMES[entry->fault] : "UNKNOWN";
			const char *subsys_name = (entry->subsystem < SUBSYS_NAMES_COUNT)
			                          ? SUBSYS_NAMES[entry->subsystem] : "UNKNOWN";
			int len = snprintf(msg, sizeof(msg),
					"[%lu] FAULT: %s | SUBSYS: %s | RETRY: %d\n",
					entry->timestamp, fault_name, subsys_name,
					(int)entry->retry_count);

			UINT written;
			ret = f_write(&SDFile, msg, (UINT)len, &written);
			if (ret != FR_OK || written != (UINT)len) {
			    fault = FAULT_STORAGE_FAILURE;
			}

			if (f_sync(&SDFile) != FR_OK) fault = FAULT_STORAGE_FAILURE;
			if (f_close(&SDFile) != FR_OK) fault = FAULT_STORAGE_FAILURE;
    	}

    	else {
    	    fault = FAULT_STORAGE_FAILURE;
    	}
		f_mount(NULL, (TCHAR const*)SDPath, 0);
	}

    power_domain_set(SDCARD_EN_PORT, SDCARD_EN_PIN, GPIO_PIN_RESET);

    return fault;
}

/* Fallback if the sd card logging failed - cyclic buffer */
FaultType log_fault_to_buffer(const FaultLog *entry)	{
	if (fault_buf_head < FAILED_LOG_BUFFER)	{
		Failed_Fault_Logs[fault_buf_head++] = *entry;
	}
	else	{
		fault_buf_head = 0;
		Failed_Fault_Logs[fault_buf_head++] = *entry;
	}
	return FAULT_NONE;
}

FRESULT RET;
FaultType flush_buffer_to_sd(void)
{
    if (s_buf_head == 0) return FAULT_NONE;

    FaultType result = init_power_domain(SDCARD_EN_PORT, SDCARD_EN_PIN,
										SDCARD_FLT_PORT, SDCARD_FLT_PIN,
										DELAY_SDCARD_SETTLE_MS,
										FAULT_LOAD_SWITCH_SDCARD);
    if (result != FAULT_NONE) return result;

    if ( f_mount(&SDFatFS, (TCHAR const*)SDPath, 1) == FR_OK) {
        if (f_open(&SDFile, "DATA.CSV", FA_OPEN_APPEND | FA_WRITE) == FR_OK) {
            for (uint8_t i = 0; i < s_buf_head; i++) {
                /* Verify each record's CRC before writing to catch RAM corruption */
                if (verify_record_crc(&s_record_buf[i]) != FAULT_NONE) {
                    result = FAULT_CRC_MISMATCH;
                    break;
                }
                char line[160];
                const char* status_str = (s_record_buf[i].op_status < FAULT_NAMES_COUNT) ?
                                         FAULT_NAMES[s_record_buf[i].op_status] : "UNKNOWN";

                int len = snprintf(line, sizeof(line),
                    "[%lu] DIFF: %.4f V | STD: %.4f | TEMP: %.2f C | STAT: %s | CRC: 0x%08lX\n",
                    s_record_buf[i].timestamp,
                    s_record_buf[i].adc_differential,
                    s_record_buf[i].adc_stddev,
                    s_record_buf[i].temperature_c,
                    status_str,
                    s_record_buf[i].crc32);

                printf("%s", line);
                UINT written;
                if (f_write(&SDFile, line, (UINT)len, &written) != FR_OK
                    || written != (UINT)len)
                {
                    result = FAULT_STORAGE_FAILURE;
                    break;
                }
            }
            f_sync(&SDFile);
            f_close(&SDFile);
        } else {
            result = FAULT_STORAGE_FAILURE;
        }
        f_mount(NULL, (TCHAR const*)SDPath, 0);
    } else {
        result = FAULT_STORAGE_FAILURE;
    }

    power_domain_set(SDCARD_EN_PORT, SDCARD_EN_PIN, GPIO_PIN_RESET);
    if (result == FAULT_NONE) s_buf_head = 0;
    return result;
}

/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 10 — Fault handler
 * ══════════════════════════════════════════════════════════════════════ */

void fault_handler(FaultType fault, SubSystem subsystem)
{
    /* 0. Stop acquisition timer if it is running */
    HAL_TIM_Base_Stop_IT(&htim2);

    /* 1. Update persistent fault manager */
    g_fault_mgr.last_fault      = fault;
    g_fault_mgr.last_subsystem  = subsystem;
    g_fault_mgr.retry_count++;
    g_fault_mgr.total_faults++;

    /* 1. Prepare the entry */
	FaultLog entry = {
		.timestamp      = rtc_now(),
		.fault          = fault,
		.subsystem      = subsystem,
		.state_at_fault = g_daq.state,
		.retry_count    = g_fault_mgr.retry_count
	};

	/* 2. Get readable strings for the Fault, Subsystem, and State */
	const char* f_name     = (entry.fault < FAULT_NAMES_COUNT) ? FAULT_NAMES[entry.fault] : "UNKNOWN";
	const char* sub_name   = (entry.subsystem < SUBSYS_NAMES_COUNT) ? SUBSYS_NAMES[entry.subsystem] : "UNKNOWN";
	const char* state_name = (entry.state_at_fault < STATE_NAMES_COUNT) ? STATE_NAMES[entry.state_at_fault] : "UNKNOWN";

	/* 3. Get Human Readable Time */
	char time_buffer[50];
	date_and_time(time_buffer);

    /* 4. Safe-state: all non-essential domains off regardless of fault type */
    disable_all_domains();

	/* 5. Format a professional Warning Block for Hercules */
	printf("\n>>> SYSTEM FAULT DETECTED <<<\n");
	printf("Time      : %s\n", time_buffer);
	printf("Fault     : %s\n", f_name);
	printf("Subsystem : %s\n", sub_name);
	printf("DAQ State : %s\n", state_name);
	printf("Retry #   : %d\n", (int)entry.retry_count);

	if (entry.retry_count >= FAULT_RETRY_LIMIT) {
		printf("ACTION    : Maximum Retries Exceeded. Entering STOP Mode.\n");
	} else {
		printf("ACTION    : Attempting Warm Recovery...\n");
	}
	printf("------------------------------\n");

	/* 6. Log to SD with full context */
	printf("Attempting to log data into microSD...\n");
	fault = log_fault_to_sd(&entry);
	if (fault != FAULT_NONE) {
		printf("%-16s : %s\n", "Storage Fault",
		       (fault < FAULT_NAMES_COUNT) ? FAULT_NAMES[fault] : "UNKNOWN");
		printf("%-16s : Saving fault to RAM persistent buffer\n", "Fallback");
		(void)log_fault_to_buffer(&entry);
	}

    /* 7. Atomically clear the ISR latch now that the fault is fully handled */
	__disable_irq();
	g_pending_fault.type 		= FAULT_NONE;
	g_pending_fault.subsystem 	= SUBSYS_PROCESSOR;
	__enable_irq();

    /* 8. Retry vs abort decision (§1.6.3) */
    if (g_fault_mgr.retry_count < FAULT_RETRY_LIMIT) {
        /* Transient: short delay then re-attempt from INIT */
        HAL_Delay(2000u);
        g_daq.state = SYS_INIT;
    } else {
        /* Persistent: give up this cycle, sleep until next RTC alarm */
        g_fault_mgr.retry_count = 0;   /* Reset for next scheduled cycle */
        g_daq.state = SYS_STOP;
    }
}


/* ══════════════════════════════════════════════════════════════════════
 *  SECTION 11 — Power management
 * ══════════════════════════════════════════════════════════════════════ */

void disable_all_domains(void)
{
    power_domain_set(EXCITE_EN_PORT, EXCITE_EN_PIN, GPIO_PIN_RESET);
    HAL_Delay(DELAY_DOMAIN_GAP_MS);
    power_domain_set(DETECT_EN_PORT, DETECT_EN_PIN, GPIO_PIN_RESET);
    HAL_Delay(DELAY_DOMAIN_GAP_MS);
    power_domain_set(SDCARD_EN_PORT, SDCARD_EN_PIN, GPIO_PIN_RESET);
}

/**
 * iwdg_kick()
 *
 * Refresh the independent watchdog.
 */
void iwdg_kick(void)
{
    HAL_IWDG_Refresh(&hiwdg);
}

void enter_stop_mode(void)
{
	/* Kick watchdog last thing before sleeping — ensures a clean cycle
	 * is what resets the counter, not a mid-fault sleep */
	iwdg_kick();

    /* Final safety: confirm all switched domains are off */
    disable_all_domains();

    /* Clear any stale wakeup flags */
    __HAL_PWR_CLEAR_FLAG(PWR_FLAG_WU);

    /* Deactivate first to ensure a clean start of the 60s counter */
    HAL_RTCEx_DeactivateWakeUpTimer(&hrtc);

    // Force the ADC back to Reset State (Clears registers)
    HAL_ADC_DeInit(&hadc1);

    /* Program RTC wakeup timer: 60 s between measurement cycles */
    __HAL_RTC_WAKEUPTIMER_CLEAR_FLAG(&hrtc, RTC_FLAG_WUTF);
    HAL_RTCEx_SetWakeUpTimer_IT(&hrtc, 60u, RTC_WAKEUPCLOCK_CK_SPRE_16BITS);

    char time_buf[50];

	date_and_time(time_buf);
	printf("\n[%s] INFO: Entering Stop Mode 2 (Target: 60s sleep)...\n", time_buf);

	/* Suspend SysTick so the periodic 1 ms interrupt does not prevent sleep */
    HAL_SuspendTick();

    /* Enter Stop 2 mode — deepest retention state on L476 (§1.7) */
    HAL_PWREx_EnterSTOP2Mode(PWR_STOPENTRY_WFI);

    /* ── System sleeps here until RTC alarm fires ── */

    /* Restore clocks immediately on wake (HSI starts after Stop 2) */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_SET);
    SystemClock_Config();

    /* Re-init UART to sync with the restored clock */
	// This resets the UART baud rate and peripheral clock
    MX_USART2_UART_Init();

	/* Resume SysTick for HAL_Delay and other timing */
	HAL_ResumeTick();

	/* 4. Log the exact moment of wakeup */
	date_and_time(time_buf);
	printf("[%s] INFO: Waking Up From Stop Mode.\n", time_buf);
	printf("--------------------------------------------------\n");

	// Re-initialize ADC Peripheral Configuration
	MX_ADC1_Init();
}

/* Debug SD card */
void debug_dump_sd(void) {
    if (f_open(&SDFile, "DATA.CSV", FA_READ) == FR_OK) {
        char line[128];
        printf("--- SD CARD DATA DUMP ---\n");
        while (f_gets(line, sizeof(line), &SDFile)) {
            printf("%s", line); // Send the line to your PC terminal
        }
        f_close(&SDFile);
        printf("--- END OF DUMP ---\n");
    }
}
